# Generated by Django 5.1.7 on 2025-03-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onetime_trans_id', models.IntegerField(blank=True, null=True)),
                ('recurring_trans_id', models.IntegerField(blank=True, null=True)),
                ('num_item', models.IntegerField()),
                ('items_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bought_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrudLogging',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.TextField()),
                ('x_requested_with', models.TextField()),
            ],
            options={
                'db_table': 'crud_logging',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.IntegerField()),
                ('attr_name', models.TextField()),
                ('attr_value', models.TextField()),
            ],
            options={
                'db_table': 'item_attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('item_desc', models.TextField(blank=True, null=True)),
                ('item_image', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTypes',
            fields=[
                ('item_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type_name', models.TextField()),
            ],
            options={
                'db_table': 'item_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginsLoggin',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_type', models.TextField()),
                ('browser', models.TextField()),
                ('cpu_arch', models.TextField()),
                ('host', models.TextField()),
                ('origin', models.TextField()),
            ],
            options={
                'db_table': 'logins_logging',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnetimeTrans',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('item_count', models.IntegerField()),
                ('cost_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'onetime_trans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringTrans',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('month_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'recurring_trans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringTransPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_rcvd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_rcvd', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recurring_trans_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('user_email', models.TextField()),
                ('user_pass', models.TextField()),
                ('birthdate', models.DateField()),
                ('address', models.TextField()),
                ('phone_num', models.TextField()),
                ('role', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
